[eth]
    txs = ["L2ContractDeployment", "L2ContractPutCall", "L2ContractGetCall"]

[L2ContractDeployment]
    type = "L2"
    httpPath = ""
    chainID = 420
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 1
    totalNumber = 1
    delay = 0
    l1Sender = ""
    l1RollupTxId = 0
    sigHashType = 0
    queueOrigin = 0

[L2ContractPutCall]
    type = "L2"
    httpPath = ""
    chainID = 420
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 15
    totalNumber = 1
    delay = 60
    l1Sender = ""
    l1RollupTxId = 0
    sigHashType = 0
    queueOrigin = 0

[L2ContractGetCall]
    type = "L2"
    httpPath = ""
    chainID = 420
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 60
    totalNumber = 2
    delay = 30
    l1Sender = ""
    l1RollupTxId = 0
    sigHashType = 0
    queueOrigin = 0

[log]
    level = "info"
    file = ""
