[eth]
    txs = ["L2ContractDeployment", "L2ContractPutCall", "L2ContractGetCall"]

[L2ContractDeployment]
    type = "L2"
    httpPath = ""
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 1
    totalNumber = 1
    chainID = 420

[L2ContractPutCall]
    type = "L2"
    httpPath = ""
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 15
    totalNumber = 1500
    chainID = 420

[L2ContractGetCall]
    type = "L2"
    httpPath = ""
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 15
    totalNumber = 1500
    chainID = 420

[GethTx]
    type = "geth"
    httpPath = ""
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 0
    totalNumber = 0
    chainID = 1

[EIP1559]
    type = "1559"
    httpPath = ""
    to = ""
    amount = "0"
    gasLimit = 0
    gasPremium = "0"
    feeCap = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    frequency = 0
    totalNumber = 0

[L1ToL2]
    type = "L2"
    httpPath = ""
    to = ""
    amount = "0"
    gasLimit = 0
    gasPrice = "0"
    data = ""
    senderKeyPath = ""
    writeSenderPath = ""
    l1Sender = ""
    l1RollupTxId = 0
    sigHashType = 0
    frequency = 0
    totalNumber = 0

[log]
    level = "info"
    file = ""
